### ISSUE TITLE
Group icon

### ISSUE THREAD

**Issue by Rishabh04-02** [awesome-css-group/awesome-css#145]
## What is this issue about?
>  Mark all the applicable options and give a brief description for each of them.
- [x] It a request to add a new feature/content.
>  Request to add a group icon.

Hey, should we set this image as our group icon?
![awesome css](https://user-images.githubusercontent.com/12505795/38858223-bf9c6ca4-4248-11e8-8043-9eab996afc4d.png)

**Comment by sotayamashita** [comment]
@Rishabh04-02 Looks good. Why do you pick pentagon?

**Comment by Rishabh04-02** [comment]
Pentagon because,
1. Its a default shape in Adobe Photoshop, hence easy to work with.
2. The reference Logo I used was of similar shape.

**Comment by troxler** [comment]
I already gave it a thumbs-up. I also wondered about the shape, but I don't really care about the icon.

**Comment by sotayamashita** [comment]
@troxler OK :smile:

@Rishabh04-02 I uploaded a profile image. Thx a lot :100:
