### ISSUE TITLE
Would csscontest.com make sense on the list?

### ISSUE THREAD

**Issue by vicnicius** [awesome-css-group/awesome-css#190]
## What is this issue about?
>  Mark all the applicable options and give a brief description for each of them.
- [x] It a request to add a new feature/content.

I recently created https://github.com/bitsofart/contest, so a bit of self-promotion here 🙈. I was wondering if it would fit the criteria of this list, probably on the miscellaneous topic. From my perspective, it matches both criteria C and D, but I'm naturally biased.

**Comment by Rishabh04-02** [comment]
⚠️ This experimental project is still on its early test phase.

Once this becomes stable, you can add it here.

**Comment by vicnicius** [comment]
Makes sense. Thanks.

**Comment by Rishabh04-02** [comment]
you are welcome.
